# So we get the new IP address
- meta: refresh_inventory

# If this returns true, skip the rest of provisioning.
- name: Check if Ansible user exists
  command: ssh -q -o BatchMode=yes -o ConnectTimeout=3 {{ ansible_user_2 }}@{{ ansible_host }} "echo OK"
  changed_when: false
  failed_when: false
  register: check_ansible_user

- block:
  - name: Wait for VM to listen on port 22
    wait_for:
      state: started
      host: "{{ ansible_host }}"
      port: 22

  - name: Add an Ansible user
    connection: ssh
    user: 
      name: "{{ ansible_user_2 }}"
      generate_ssh_key: yes
    tags: bootstrap

  - name: Add Ansible user to sudo
    connection: ssh
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^{{ ansible_user_2 }}"
      line: "{{ ansible_user_2 }} ALL=(ALL) NOPASSWD: ALL"
      validate: 'visudo -cf %s'
    tags: bootstrap

  - name: Add authorized keys to Ansible user
    connection: ssh
    authorized_key:
      user: "{{ ansible_user_2 }}"
      key: "{{ ansible_authorized_keys }}"
  when: check_ansible_user.rc != 0
